name: DevOpsApp

on: 
    push:
        branches: [main]
jobs:
    deploy:
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRECT_ACCESS_KEY}}
            AWS_SESSION_TOKEN: ${{ secrets.ASW_SESSION_TOKEN }}
            AWS_DEFAULT_REGION: us-east-1
        runs-on: ubuntu-latest
        steps:
          
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v3

         - name: Terraform init
           working-directory: terraform
           run: terraform init

         - name: Terraform apply
           working-directory: terraform
           run: terraform apply -auto-approve

         - name: Get EC2 public IP
           id: tf-ip
           working-directory: terraform
           run: echo "ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

        
        
        
        
        
        
        
        
        
      


        